
-- 第5回 JOIN文

-- テーブルに指定の条件で別のテーブルをつなげる文

-- 元のテーブル（カラム名「COLUMN3」を持つテーブル「UNION_T」）
SELECT 
    COLUMN3
FROM
(
	SELECT 1 AS COLUMN1
	UNION 
	SELECT 2 AS COLUMN2
) AS UNION_T(COLUMN3)

-- 結合後のテーブル（テーブル「UNION_T」の「COLUMN3」とテーブル「JOIN_T」の「COLUMN3」が同じ行を結合）
-- どのテーブルの値かを「UNION_T.COLUMN3」「JOIN_T.COLUMN3」とテーブル名をつけることで区別
-- しかし、INNER JOINだとJOIN_Tで該当しない行でNULLになると行（1行目）自体なくなってしまう
SELECT 
    UNION_T.COLUMN3 AS UNION_T_VALUE,
	JOIN_T.COLUMN3  AS JOIN_T_VALUE
FROM
(
	SELECT 1 AS COLUMN1
	UNION 
	SELECT 2 AS COLUMN2
) AS UNION_T(COLUMN3)
INNER JOIN
(
	SELECT 2 AS COLUMN1
	UNION 
	SELECT 3 AS COLUMN2
) AS JOIN_T(COLUMN3)
	ON  JOIN_T.COLUMN3 = UNION_T.COLUMN3

-- NULLでも表示する場合には、LEFT JOINを用いる
SELECT 
    UNION_T.COLUMN3 AS UNION_T_VALUE,
	JOIN_T.COLUMN3  AS JOIN_T_VALUE
FROM
(
	SELECT 1 AS COLUMN1
	UNION 
	SELECT 2 AS COLUMN2
) AS UNION_T(COLUMN3)
LEFT JOIN
(
	SELECT 2 AS COLUMN1
	UNION 
	SELECT 3 AS COLUMN2
) AS JOIN_T(COLUMN3)
	ON  JOIN_T.COLUMN3 = UNION_T.COLUMN3