
-- 第5回 VALUES文

-- SELECT文を用いずにテーブルを作る文
-- UNION文で書いていたSQLは以下の通りに書くことができる

SELECT 
    COLUMN3
FROM
( 
	VALUES (1),(2)
) AS VALUES_T(COLUMN3)

-- 結合後のテーブルも見やすくなる
SELECT 
    VALUES_T.COLUMN3 AS VALUES_T_VALUE,
	JOIN_T.COLUMN3  AS JOIN_T_VALUE
FROM
(
	VALUES (1),(2)
) AS VALUES_T(COLUMN3)
LEFT JOIN
(
	VALUES (2),(3)
) AS JOIN_T(COLUMN3)
	ON  JOIN_T.COLUMN3 = VALUES_T.COLUMN3

-- LEFT JOINを用いず、この結果を以下の形で表示できる。
SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,2)
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)

