
-- 第9回 APPLY文

-- テーブルにSQLの実行結果をそのまま結合する文

-- 全ての行に2が結合される。
SELECT 
    VALUES_T.COLUMN1 AS VALUES__T_VALUE,
	CROSS_T.COLUMN1  AS CROSS__T_VALUE
FROM
( 
	VALUES (1),(2)
) AS VALUES_T(COLUMN1)
CROSS APPLY
(
	SELECT 2 AS COLUMN1
) AS CROSS_T

-- 指定の条件で結合する場合は、WHERE文を以下のように中で使う。
-- CROSS APPLYだとCROSS_TがNULLの場合行自体がなくなってしまう
SELECT 
    VALUES_T.COLUMN1 AS VALUES__T_VALUE,
	CROSS_T.COLUMN1  AS CROSS__T_VALUE
FROM
( 
	VALUES (1),(2)
) AS VALUES_T(COLUMN1)
CROSS APPLY
(
	-- AS文のカラム名は一度SELECT文を実行しないと検索条件で使えないため、
	-- 一旦SEARCH_TにしてからWHEREしている。
	SELECT COLUMN1 FROM( SELECT 2 AS COLUMN1 ) AS SEARCH_T
	WHERE COLUMN1 = VALUES_T.COLUMN1
) AS CROSS_T

-- NULLでも行を残す場合は、OUTER APPLYを用いる
SELECT 
    VALUES_T.COLUMN1 AS VALUES__T_VALUE,
	CROSS_T.COLUMN1  AS CROSS__T_VALUE
FROM
( 
	VALUES (1),(2)
) AS VALUES_T(COLUMN1)
OUTER APPLY
(
	SELECT COLUMN1 FROM( SELECT 2 AS COLUMN1 ) AS SEARCH_T
	WHERE COLUMN1 = VALUES_T.COLUMN1
) AS CROSS_T

