
-- 第9回 CROSS APPLY文

-- テーブルにSQLの実行結果をそのまま結合する文

-- 全ての行に2が結合される。
SELECT 
    VALUES_T.COLUMN1 AS VALUES__T_VALUE,
	CROSS_T.COLUMN1  AS CROSS__T_VALUE
FROM
( 
	VALUES (1),(2)
) AS VALUES_T(COLUMN1)
CROSS APPLY
(
	SELECT 2 AS COLUMN1
) AS CROSS_T

-- 指定の条件で結合する場合は、

-- 結合後のテーブルも見やすくなる
SELECT 
    VALUES_T.COLUMN3 AS VALUES_T_VALUE,
	JOIN_T.COLUMN3  AS JOIN_T_VALUE
FROM
(
	VALUES (1),(2)
) AS VALUES_T(COLUMN3)
LEFT JOIN
(
	VALUES (2),(3)
) AS JOIN_T(COLUMN3)
	ON  JOIN_T.COLUMN3 = VALUES_T.COLUMN3

-- LEFT JOINを用いず、この結果を以下の形で表示できる。
SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,2)
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)

