
-- 第10回 NULLの扱い

-- NULLとはデータがないことを示す言葉

-- NULLかどうかはIS NULLで判別できる。
-- （NULLは空欄と別物であるため、空欄の行は表示されない）
SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,''),(3,'X')
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)
WHERE JOIN_T_VALUE IS NULL

-- NULLを空欄として表示するにはISNULL関数で空白に置き換える必要がある
SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,''),(3,'X')
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)
WHERE ISNULL(JOIN_T_VALUE,'') = ''

-- 例としてXを含まない行を出すには!=あるいはNOTを用いるが、
-- ISNULL関数を利用しないとNULLを含む比較は必ずFALSEになるため行が表示されない
SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,''),(3,'X')
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)
WHERE JOIN_T_VALUE != 'X'

SELECT 
    VALUES_T_VALUE,
	JOIN_T_VALUE
FROM
(
	VALUES (1,NULL),(2,''),(3,'X')
) AS VALUES_T(VALUES_T_VALUE,JOIN_T_VALUE)
WHERE JOIN_T_VALUE NOT LIKE '%X%'